data:
  path: 'sample-data/data'

modules:
  model_initializer: 'sample-data.wrapper-sample'
  data_preprocessor: 'sample-data.wrapper-sample'
  model_trainer: 'sample-data.wrapper-sample'
  model_tester: 'sample-data.wrapper-sample'
  model_evaluator: 'sample-data.wrapper-sample'